### ISSUE TITLE
from SD import text2img

### ISSUE THREAD

**Issue by wtc9806** [zzjchen/Tailored-Visions#1]
Hi authors,

Thanks for the great job. I am a little bit confused about main.py. How to install SD?

**Comment by zzjchen** [comment]
@wtc9806 Thanks for the issue.
It appears that a file "SD.py" was missing, but we have now uploaded it.

**Comment by wtc9806** [comment]
Ok，Thanks!

**Comment by wtc9806** [comment]
@zzjchen I would like to ask if the image data in this dataset is open source. I downloaded it through the link , but without success.
![image](https://github.com/zzjchen/Tailored-Visions/assets/85442237/f4c98479-bddb-48b0-bed1-db273511b321)

**Comment by zzjchen** [comment]
@wtc9806 I know what's going on.
Some of the original images are stored on aliyun, which result in download links with something like "?Expires=xxxxxxxx&OSSAccessKeyId=xxxxxxxxx&Signature=xxxxxxxxxx" at the end, which might be the cause.
A quick solution for you is to remove these from the link, and only keep the "https://westlake-image.oss-cn-hangzhou.aliyuncs.com/gallery/xxxx/xxxxxxx.jpeg" which should be able to download successfully.
We will fix this problem soon and offer a new link for dataset soon.

**Comment by zzjchen** [comment]
We have updated the link to our dataset, and the issue should be resolved now.

**Comment by wtc9806** [comment]
Got it! Thank you!
